import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "react-datepicker/dist/react-datepicker-cssmodules.css";
import "react-datepicker/dist/react-datepicker.css";

import { Toast } from "@/components";
import NextAuthProvider from "@/plugins/next-auth/provider";
import CustomSWRConfig from "@/plugins/swr";
import "@/styles/globals.css";
const inter = Inter({ variable: "--font-sans", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Test DOT Indonesia - Made by Muhammad Zidane Al - Saadawi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomSWRConfig>
          <NextAuthProvider>{children}</NextAuthProvider>
        </CustomSWRConfig>
        <Toast />
      </body>
    </html>
  );
}
